Output Schema
superagent-ai/superagent pull request #922
Opened 2024-03-28 20:27 UTC by elisalimli

## Summary

Fixes #918

## Test plan

Here's an example SAML that I tested to scrape structured data from Amazon.com

```yaml
workflows:
  - superagent:
      llm: gpt-3.5-turbo-1106
      name: Browser assistant
      intro: 👋 Hi there! How can I help search for answers on the internet.
      tools:
        - scraper:
            name: browser
            use_for: searching the internet
            metadata:
              apiKey: 9EA0OH7T2LXAXHPV3K036MN192XQZ2DRMP2XA9QC0KF2LBU9XCMXK8CJREIU5AVNOYPMHJD4Y2AEF8NR
      prompt: Use the browser to answer any questions
      output_schema:
        type: array
        items:
          type: object
          required:
            - id
            - name
          properties:
            id:
              type: integer
            product_name:
              type: integer
            product_price:
              type: string
```

```
  "input": "i need product name, product price, store name from https://www.amazon.com/s?k=apple+m3&crid=2CSLNASAYI715&sprefix=apple+mc%2Caps%2C376&ref=nb_sb_noss_2",
```

2024-03-28 22:05 UTC, homanp reviewed
Left a comment @elisalimli

2024-03-28 22:05 UTC, homanp commented on libs/superagent/prisma/migrations/20240328135202_add_output_schema_field_agents_table/migration.sql
Why do we need to store this separately? It's already stored in the config?

2024-03-29 04:45 UTC, homanp requested changes
@elisalimli this needs work with the REST API and SDKs as well. could you add that as well? On the workflow `invoke` function.

2024-03-29 05:46 UTC, elisalimli commented
> @elisalimli this needs work with the REST API and SDKs as well. could you add that as well? On the workflow `invoke` function.

@homanp it will work on the SDK too. We just call our existing api_endpoints in SAML. So whatever works there will work on REST API/SDK

2024-03-29 05:47 UTC, elisalimli commented on libs/superagent/prisma/migrations/20240328135202_add_output_schema_field_agents_table/migration.sql
Where is it stored? Please point to sources if I missed any.

2024-03-29 06:04 UTC, homanp commented
> > @elisalimli this needs work with the REST API and SDKs as well. could you add that as well? On the workflow `invoke` function.
> 
> @homanp it will work on the SDK too. We just call our existing api_endpoints in SAML. So whatever works there will work on REST API/SDK

I don't see any `outputSchema` key work invoking workflows in the REST API.

2024-03-29 06:06 UTC, elisalimli commented
> > > @elisalimli this needs work with the REST API and SDKs as well. could you add that as well? On the workflow `invoke` function.
> > 
> > 
> > @homanp it will work on the SDK too. We just call our existing api_endpoints in SAML. So whatever works there will work on REST API/SDK
> 
> I don't see any `outputSchema` key work invoking workflows in the REST API.

Yes, we don't. I thought it's redundant to receive outputSchema every time. Instead we're storing in the database and read from there.

2024-03-29 18:37 UTC, homanp requested changes

2024-03-29 18:37 UTC, homanp commented on libs/superagent/app/api/workflow_configs/data_transformer.py
> +        print(database, database_provider)
Remove

2024-03-29 18:39 UTC, homanp requested changes
<img width="1901" alt="Screenshot 2024-03-29 at 11 38 52" src="https://github.com/superagent-ai/superagent/assets/2464556/b9aabc86-99d1-4813-bdba-2829d79bdce4">

2024-03-30 19:13 UTC, homanp approved these changes

2024-03-30 19:23 UTC, merged