Implement Olostep API for better scraping (using real browsers)
superagent-ai/superagent pull request #931
Opened 2024-04-03 23:32 UTC by devKingMe

## Summary

Implemented the [Olostep API](https://www.olostep.com/)

2024-04-04 17:19 UTC, homanp commented
@elisalimli mind reviewing this?

2024-04-04 17:45 UTC, elisalimli requested changes
@devKingMe Left some small comments, otherwise looks well, thanks!

2024-04-04 17:45 UTC, elisalimli commented on libs/superagent/app/api/workflow_configs/saml_schema.py
> +    advanced_scraper: Optional[Tool]
Let's rename this to `olostep` instead of `advanced_scraper`

2024-04-04 17:45 UTC, elisalimli commented on libs/superagent/app/tools/advanced_scraper.py
> +            expandMarkdown = False
Let's do instead:

```suggestion

        saveHtml = format == "html"
        saveMarkdown = format == "markdown"
        expandHtml = format == "html"
        expandMarkdown = format == "markdown"
        
 ```

2024-04-04 18:03 UTC, devKingMe commented on libs/superagent/app/api/workflow_configs/saml_schema.py
> +    advanced_scraper: Optional[Tool]
@elisalimli I picked that name because it may be easier for people to recognize instead of a random company name (for example scraper instead of scraping bee). Would love to chat more though!

2024-04-04 18:04 UTC, devKingMe commented on libs/superagent/app/tools/advanced_scraper.py
> +            expandMarkdown = False
makes sense, will send a commit now, thanks!

2024-04-04 18:15 UTC, devKingMe commented on libs/superagent/app/tools/advanced_scraper.py
> +            expandMarkdown = False
resolved in 99238369157ee71bedec68b7bc0fb8d4d0ff006e

2024-04-04 18:44 UTC, homanp commented on libs/superagent/app/api/workflow_configs/saml_schema.py
> +    advanced_scraper: Optional[Tool]
@elisalimli @devKingMe `advanced_scraper` is OK. Similar to `scraper` and ScrapingBee

2024-04-05 17:58 UTC, elisalimli approved these changes
lgtm!

2024-04-05 17:58 UTC, homanp approved these changes

2024-04-05 17:58 UTC, merged