[refactor] Agent Classes & Parallel function calling for LLM Agent
superagent-ai/superagent pull request #965
Opened 2024-04-18 04:37 UTC by elisalimli

## Summary

This PR refactors AgentBase, LangchainAgent, LLMAgent.

As well, I have added parallel function calling using native OpenAI function calling instead of relying Langchain implementation. Previously, parallel function calling was not working, because we were setting return_direct to True and we were always returning the first function call before even calling the second or so on.

2024-04-18 11:13 UTC, homanp requested changes
![Uploading Screenshot 2024-04-18 at 13.13.11.png…]()

2024-04-18 11:28 UTC, homanp requested changes
Please use native function calling here for the specific model. The hybrid approach won't be necessary since most models support function calling. 

<img width="840" alt="Screenshot 2024-04-18 at 13 27 42" src="https://github.com/superagent-ai/superagent/assets/2464556/2d737053-0fc6-4282-bd7f-b8ad228f1aee">

2024-04-18 11:37 UTC, elisalimli commented
> Seems to be broken in the UI.
> 
> <img alt="Screenshot 2024-04-18 at 13 13 48" width="1696" src="https://private-user-images.githubusercontent.com/2464556/323578586-54bcaf13-62a1-4a98-a37c-33c799d53e50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDA0MjcsIm5iZiI6MTcxMzQ0MDEyNywicGF0aCI6Ii8yNDY0NTU2LzMyMzU3ODU4Ni01NGJjYWYxMy02MmExLTRhOTgtYTM3Yy0zM2M3OTlkNTNlNTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MThUMTEzNTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmU5MDIxN2JkN2UxZTNhY2ZhNjU5NmVjZWQxZTk5ZTQ0ZDljNGEzNjBiNTdmNTk2ZGY4YzZlZmVkMTgxNDQ3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.skkIxaJElMrasZfHlLXkBp2lt4gcdpwqOVlmA1ZdRzY">

I will create a new issue for it and solve. That was not caused but this PR, i have seen it before to.

2024-04-29 08:53 UTC, homanp approved these changes

2024-04-29 09:11 UTC, merged